"""Added user table.

Revision ID: a260d3799d2c
Revises:
Create Date: 2025-12-05 13:44:53.287552

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a260d3799d2c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("users",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("email", sa.String(), nullable=True),
    sa.Column("password", sa.String(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
