"""initial schema.

Revision ID: d1917ffcec0a
Revises:
Create Date: 2026-05-12 21:24:35.094708

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1917ffcec0a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("genre", sa.String(length=255), nullable=False),
        sa.Column("director", sa.String(length=255), nullable=False),
        sa.Column("critic_rating", sa.Integer(), nullable=False),
        sa.Column("age_rating", sa.String(length=10), nullable=False),
        sa.Column("release_date", sa.Date(), nullable=False),
        sa.Column("rental_price", sa.Float(), nullable=False),
        sa.Column("copies_available", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_movies")),
        schema="app",
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "name",
            sa.Enum("STAFF", "CUSTOMER", name="role_name", schema="app"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("name", name=op.f("uq_roles_name")),
        schema="app",
    )
    op.create_table(
        "movie_external_ids",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["app.movies.id"],
            name=op.f("fk_movie_external_ids_movie_id_movies"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_movie_external_ids")),
        sa.UniqueConstraint("provider", "external_id", name="uq_movie_external_id_per_provider"),
        schema="app",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["app.roles.id"], name=op.f("fk_users_role_id_roles")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        schema="app",
    )
    op.create_table(
        "rentals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "COMPLETED", "LATE", "REMOVED", name="rental_status", schema="app"),
            nullable=False,
        ),
        sa.Column("expected_return_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("returned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("staff_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["app.users.id"],
            name=op.f("fk_rentals_customer_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["app.movies.id"],
            name=op.f("fk_rentals_movie_id_movies"),
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["app.users.id"],
            name=op.f("fk_rentals_staff_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rentals")),
        schema="app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rentals", schema="app")
    op.drop_table("users", schema="app")
    op.drop_table("movie_external_ids", schema="app")
    op.drop_table("roles", schema="app")
    op.drop_table("movies", schema="app")
    # ### end Alembic commands ###
